spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/todolist
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
