name: Current date&time in Russian Federation, Moscow, MIPT, HSSE, 1 term!

on:
  push
  pull_request

jobs:
  HSSE_Date:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from MIPT HSSE. Check date&time below.
        run: |
          date +"DATE: %F"
          date +"TIME: %T"
